services:
- name: multiple-http-ports
  env: go
  type: web
  buildCommand: go build -tags netgo -ldflags '-s -w' -o app
  startCommand: ./app
  healthCheckPath: /healthz
  envVars:
    - key: PORT
      value: 9090
